// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mocks

import (
	"sync"

	"github.com/fredbi/git-janitor/internal/store"
)

// Ensure that MockStore does implement store.Store.
// If this is not the case, regenerate this file with mockery.
var _ store.Store = &MockStore{}

// MockStore is a mock implementation of store.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked store.Store
//		mockedStore := &MockStore{
//			ClearBucketFunc: func(bucket string) error {
//				panic("mock out the ClearBucket method")
//			},
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			DeleteFunc: func(bucket string, key string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(bucket string, key string) ([]byte, error) {
//				panic("mock out the Get method")
//			},
//			PutFunc: func(bucket string, key string, value []byte) error {
//				panic("mock out the Put method")
//			},
//			ScanFunc: func(bucket string, prefix string, fn func(key []byte, value []byte) bool) error {
//				panic("mock out the Scan method")
//			},
//		}
//
//		// use mockedStore in code that requires store.Store
//		// and then make assertions.
//
//	}
type MockStore struct {
	// ClearBucketFunc mocks the ClearBucket method.
	ClearBucketFunc func(bucket string) error

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(bucket string, key string) error

	// GetFunc mocks the Get method.
	GetFunc func(bucket string, key string) ([]byte, error)

	// PutFunc mocks the Put method.
	PutFunc func(bucket string, key string, value []byte) error

	// ScanFunc mocks the Scan method.
	ScanFunc func(bucket string, prefix string, fn func(key []byte, value []byte) bool) error

	// calls tracks calls to the methods.
	calls struct {
		// ClearBucket holds details about calls to the ClearBucket method.
		ClearBucket []struct {
			// Bucket is the bucket argument value.
			Bucket string
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []byte
		}
		// Scan holds details about calls to the Scan method.
		Scan []struct {
			// Bucket is the bucket argument value.
			Bucket string
			// Prefix is the prefix argument value.
			Prefix string
			// Fn is the fn argument value.
			Fn func(key []byte, value []byte) bool
		}
	}
	lockClearBucket sync.RWMutex
	lockClose       sync.RWMutex
	lockDelete      sync.RWMutex
	lockGet         sync.RWMutex
	lockPut         sync.RWMutex
	lockScan        sync.RWMutex
}

// ClearBucket calls ClearBucketFunc.
func (mock *MockStore) ClearBucket(bucket string) error {
	if mock.ClearBucketFunc == nil {
		panic("MockStore.ClearBucketFunc: method is nil but Store.ClearBucket was just called")
	}
	callInfo := struct {
		Bucket string
	}{
		Bucket: bucket,
	}
	mock.lockClearBucket.Lock()
	mock.calls.ClearBucket = append(mock.calls.ClearBucket, callInfo)
	mock.lockClearBucket.Unlock()
	return mock.ClearBucketFunc(bucket)
}

// ClearBucketCalls gets all the calls that were made to ClearBucket.
// Check the length with:
//
//	len(mockedStore.ClearBucketCalls())
func (mock *MockStore) ClearBucketCalls() []struct {
	Bucket string
} {
	var calls []struct {
		Bucket string
	}
	mock.lockClearBucket.RLock()
	calls = mock.calls.ClearBucket
	mock.lockClearBucket.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *MockStore) Close() error {
	if mock.CloseFunc == nil {
		panic("MockStore.CloseFunc: method is nil but Store.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStore.CloseCalls())
func (mock *MockStore) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *MockStore) Delete(bucket string, key string) error {
	if mock.DeleteFunc == nil {
		panic("MockStore.DeleteFunc: method is nil but Store.Delete was just called")
	}
	callInfo := struct {
		Bucket string
		Key    string
	}{
		Bucket: bucket,
		Key:    key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(bucket, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedStore.DeleteCalls())
func (mock *MockStore) DeleteCalls() []struct {
	Bucket string
	Key    string
} {
	var calls []struct {
		Bucket string
		Key    string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *MockStore) Get(bucket string, key string) ([]byte, error) {
	if mock.GetFunc == nil {
		panic("MockStore.GetFunc: method is nil but Store.Get was just called")
	}
	callInfo := struct {
		Bucket string
		Key    string
	}{
		Bucket: bucket,
		Key:    key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(bucket, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedStore.GetCalls())
func (mock *MockStore) GetCalls() []struct {
	Bucket string
	Key    string
} {
	var calls []struct {
		Bucket string
		Key    string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *MockStore) Put(bucket string, key string, value []byte) error {
	if mock.PutFunc == nil {
		panic("MockStore.PutFunc: method is nil but Store.Put was just called")
	}
	callInfo := struct {
		Bucket string
		Key    string
		Value  []byte
	}{
		Bucket: bucket,
		Key:    key,
		Value:  value,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	return mock.PutFunc(bucket, key, value)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedStore.PutCalls())
func (mock *MockStore) PutCalls() []struct {
	Bucket string
	Key    string
	Value  []byte
} {
	var calls []struct {
		Bucket string
		Key    string
		Value  []byte
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}

// Scan calls ScanFunc.
func (mock *MockStore) Scan(bucket string, prefix string, fn func(key []byte, value []byte) bool) error {
	if mock.ScanFunc == nil {
		panic("MockStore.ScanFunc: method is nil but Store.Scan was just called")
	}
	callInfo := struct {
		Bucket string
		Prefix string
		Fn     func(key []byte, value []byte) bool
	}{
		Bucket: bucket,
		Prefix: prefix,
		Fn:     fn,
	}
	mock.lockScan.Lock()
	mock.calls.Scan = append(mock.calls.Scan, callInfo)
	mock.lockScan.Unlock()
	return mock.ScanFunc(bucket, prefix, fn)
}

// ScanCalls gets all the calls that were made to Scan.
// Check the length with:
//
//	len(mockedStore.ScanCalls())
func (mock *MockStore) ScanCalls() []struct {
	Bucket string
	Prefix string
	Fn     func(key []byte, value []byte) bool
} {
	var calls []struct {
		Bucket string
		Prefix string
		Fn     func(key []byte, value []byte) bool
	}
	mock.lockScan.RLock()
	calls = mock.calls.Scan
	mock.lockScan.RUnlock()
	return calls
}
