// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mocks

import (
	"sync"

	"github.com/fredbi/git-janitor/internal/registry"
)

// Ensure that MockRegistrable does implement registry.Registrable.
// If this is not the case, regenerate this file with mockery.
var _ registry.Registrable = &MockRegistrable{}

// MockRegistrable is a mock implementation of registry.Registrable.
//
//	func TestSomethingThatUsesRegistrable(t *testing.T) {
//
//		// make and configure a mocked registry.Registrable
//		mockedRegistrable := &MockRegistrable{
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedRegistrable in code that requires registry.Registrable
//		// and then make assertions.
//
//	}
type MockRegistrable struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockName sync.RWMutex
}

// Name calls NameFunc.
func (mock *MockRegistrable) Name() string {
	if mock.NameFunc == nil {
		panic("MockRegistrable.NameFunc: method is nil but Registrable.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedRegistrable.NameCalls())
func (mock *MockRegistrable) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}
