// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mocks

import (
	"context"
	"iter"
	"sync"
	"time"

	"github.com/fredbi/git-janitor/internal/config"
	"github.com/fredbi/git-janitor/internal/ifaces"
	"github.com/fredbi/git-janitor/internal/models"
	"github.com/fredbi/git-janitor/internal/quickactions"
)

// Ensure that MockEngineer does implement ifaces.Engineer.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.Engineer = &MockEngineer{}

// MockEngineer is a mock implementation of ifaces.Engineer.
//
//	func TestSomethingThatUsesEngineer(t *testing.T) {
//
//		// make and configure a mocked ifaces.Engineer
//		mockedEngineer := &MockEngineer{
//			ClearCacheFunc: func() (int, error) {
//				panic("mock out the ClearCache method")
//			},
//			CollectFunc: func(ctx context.Context, info *models.RepoInfo, opts ...models.CollectOption) *models.RepoInfo {
//				panic("mock out the Collect method")
//			},
//			CollectDetailsFunc: func(ctx context.Context, info *models.RepoInfo, scope models.ActionSuggestion) *models.RepoInfo {
//				panic("mock out the CollectDetails method")
//			},
//			EvaluateFunc: func(ctx context.Context, info *models.RepoInfo, opts ...models.EvaluateOption) (iter.Seq[models.Alert], error) {
//				panic("mock out the Evaluate method")
//			},
//			ExecuteFunc: func(ctx context.Context, info *models.RepoInfo, action models.ActionSuggestion) (models.Result, error) {
//				panic("mock out the Execute method")
//			},
//			ExecuteQuickActionFunc: func(ctx context.Context, rootIndex int, name string, params map[string]string) error {
//				panic("mock out the ExecuteQuickAction method")
//			},
//			GetActionFunc: func(name string) (ifaces.Action, bool) {
//				panic("mock out the GetAction method")
//			},
//			GetCheckFunc: func(name string) (ifaces.Check, bool) {
//				panic("mock out the GetCheck method")
//			},
//			ProviderEnabledFunc: func(provider string) bool {
//				panic("mock out the ProviderEnabled method")
//			},
//			PurgeHistoryFunc: func(olderThanDays int) (int, error) {
//				panic("mock out the PurgeHistory method")
//			},
//			QuickActionsForFunc: func(rootIndex int, subject models.SubjectKind) iter.Seq[*quickactions.QuickAction] {
//				panic("mock out the QuickActionsFor method")
//			},
//			RecentHistoryFunc: func(repoPath string, since time.Time) []models.HistoryEntry {
//				panic("mock out the RecentHistory method")
//			},
//			RefreshFunc: func(ctx context.Context, info *models.RepoInfo) *models.RepoInfo {
//				panic("mock out the Refresh method")
//			},
//			ReloadFunc: func(cfg *config.Config)  {
//				panic("mock out the Reload method")
//			},
//		}
//
//		// use mockedEngineer in code that requires ifaces.Engineer
//		// and then make assertions.
//
//	}
type MockEngineer struct {
	// ClearCacheFunc mocks the ClearCache method.
	ClearCacheFunc func() (int, error)

	// CollectFunc mocks the Collect method.
	CollectFunc func(ctx context.Context, info *models.RepoInfo, opts ...models.CollectOption) *models.RepoInfo

	// CollectDetailsFunc mocks the CollectDetails method.
	CollectDetailsFunc func(ctx context.Context, info *models.RepoInfo, scope models.ActionSuggestion) *models.RepoInfo

	// EvaluateFunc mocks the Evaluate method.
	EvaluateFunc func(ctx context.Context, info *models.RepoInfo, opts ...models.EvaluateOption) (iter.Seq[models.Alert], error)

	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context, info *models.RepoInfo, action models.ActionSuggestion) (models.Result, error)

	// ExecuteQuickActionFunc mocks the ExecuteQuickAction method.
	ExecuteQuickActionFunc func(ctx context.Context, rootIndex int, name string, params map[string]string) error

	// GetActionFunc mocks the GetAction method.
	GetActionFunc func(name string) (ifaces.Action, bool)

	// GetCheckFunc mocks the GetCheck method.
	GetCheckFunc func(name string) (ifaces.Check, bool)

	// ProviderEnabledFunc mocks the ProviderEnabled method.
	ProviderEnabledFunc func(provider string) bool

	// PurgeHistoryFunc mocks the PurgeHistory method.
	PurgeHistoryFunc func(olderThanDays int) (int, error)

	// QuickActionsForFunc mocks the QuickActionsFor method.
	QuickActionsForFunc func(rootIndex int, subject models.SubjectKind) iter.Seq[*quickactions.QuickAction]

	// RecentHistoryFunc mocks the RecentHistory method.
	RecentHistoryFunc func(repoPath string, since time.Time) []models.HistoryEntry

	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, info *models.RepoInfo) *models.RepoInfo

	// ReloadFunc mocks the Reload method.
	ReloadFunc func(cfg *config.Config)

	// calls tracks calls to the methods.
	calls struct {
		// ClearCache holds details about calls to the ClearCache method.
		ClearCache []struct {
		}
		// Collect holds details about calls to the Collect method.
		Collect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Info is the info argument value.
			Info *models.RepoInfo
			// Opts is the opts argument value.
			Opts []models.CollectOption
		}
		// CollectDetails holds details about calls to the CollectDetails method.
		CollectDetails []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Info is the info argument value.
			Info *models.RepoInfo
			// Scope is the scope argument value.
			Scope models.ActionSuggestion
		}
		// Evaluate holds details about calls to the Evaluate method.
		Evaluate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Info is the info argument value.
			Info *models.RepoInfo
			// Opts is the opts argument value.
			Opts []models.EvaluateOption
		}
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Info is the info argument value.
			Info *models.RepoInfo
			// Action is the action argument value.
			Action models.ActionSuggestion
		}
		// ExecuteQuickAction holds details about calls to the ExecuteQuickAction method.
		ExecuteQuickAction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RootIndex is the rootIndex argument value.
			RootIndex int
			// Name is the name argument value.
			Name string
			// Params is the params argument value.
			Params map[string]string
		}
		// GetAction holds details about calls to the GetAction method.
		GetAction []struct {
			// Name is the name argument value.
			Name string
		}
		// GetCheck holds details about calls to the GetCheck method.
		GetCheck []struct {
			// Name is the name argument value.
			Name string
		}
		// ProviderEnabled holds details about calls to the ProviderEnabled method.
		ProviderEnabled []struct {
			// Provider is the provider argument value.
			Provider string
		}
		// PurgeHistory holds details about calls to the PurgeHistory method.
		PurgeHistory []struct {
			// OlderThanDays is the olderThanDays argument value.
			OlderThanDays int
		}
		// QuickActionsFor holds details about calls to the QuickActionsFor method.
		QuickActionsFor []struct {
			// RootIndex is the rootIndex argument value.
			RootIndex int
			// Subject is the subject argument value.
			Subject models.SubjectKind
		}
		// RecentHistory holds details about calls to the RecentHistory method.
		RecentHistory []struct {
			// RepoPath is the repoPath argument value.
			RepoPath string
			// Since is the since argument value.
			Since time.Time
		}
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Info is the info argument value.
			Info *models.RepoInfo
		}
		// Reload holds details about calls to the Reload method.
		Reload []struct {
			// Cfg is the cfg argument value.
			Cfg *config.Config
		}
	}
	lockClearCache         sync.RWMutex
	lockCollect            sync.RWMutex
	lockCollectDetails     sync.RWMutex
	lockEvaluate           sync.RWMutex
	lockExecute            sync.RWMutex
	lockExecuteQuickAction sync.RWMutex
	lockGetAction          sync.RWMutex
	lockGetCheck           sync.RWMutex
	lockProviderEnabled    sync.RWMutex
	lockPurgeHistory       sync.RWMutex
	lockQuickActionsFor    sync.RWMutex
	lockRecentHistory      sync.RWMutex
	lockRefresh            sync.RWMutex
	lockReload             sync.RWMutex
}

// ClearCache calls ClearCacheFunc.
func (mock *MockEngineer) ClearCache() (int, error) {
	if mock.ClearCacheFunc == nil {
		panic("MockEngineer.ClearCacheFunc: method is nil but Engineer.ClearCache was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClearCache.Lock()
	mock.calls.ClearCache = append(mock.calls.ClearCache, callInfo)
	mock.lockClearCache.Unlock()
	return mock.ClearCacheFunc()
}

// ClearCacheCalls gets all the calls that were made to ClearCache.
// Check the length with:
//
//	len(mockedEngineer.ClearCacheCalls())
func (mock *MockEngineer) ClearCacheCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClearCache.RLock()
	calls = mock.calls.ClearCache
	mock.lockClearCache.RUnlock()
	return calls
}

// Collect calls CollectFunc.
func (mock *MockEngineer) Collect(ctx context.Context, info *models.RepoInfo, opts ...models.CollectOption) *models.RepoInfo {
	if mock.CollectFunc == nil {
		panic("MockEngineer.CollectFunc: method is nil but Engineer.Collect was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Info *models.RepoInfo
		Opts []models.CollectOption
	}{
		Ctx:  ctx,
		Info: info,
		Opts: opts,
	}
	mock.lockCollect.Lock()
	mock.calls.Collect = append(mock.calls.Collect, callInfo)
	mock.lockCollect.Unlock()
	return mock.CollectFunc(ctx, info, opts...)
}

// CollectCalls gets all the calls that were made to Collect.
// Check the length with:
//
//	len(mockedEngineer.CollectCalls())
func (mock *MockEngineer) CollectCalls() []struct {
	Ctx  context.Context
	Info *models.RepoInfo
	Opts []models.CollectOption
} {
	var calls []struct {
		Ctx  context.Context
		Info *models.RepoInfo
		Opts []models.CollectOption
	}
	mock.lockCollect.RLock()
	calls = mock.calls.Collect
	mock.lockCollect.RUnlock()
	return calls
}

// CollectDetails calls CollectDetailsFunc.
func (mock *MockEngineer) CollectDetails(ctx context.Context, info *models.RepoInfo, scope models.ActionSuggestion) *models.RepoInfo {
	if mock.CollectDetailsFunc == nil {
		panic("MockEngineer.CollectDetailsFunc: method is nil but Engineer.CollectDetails was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Info  *models.RepoInfo
		Scope models.ActionSuggestion
	}{
		Ctx:   ctx,
		Info:  info,
		Scope: scope,
	}
	mock.lockCollectDetails.Lock()
	mock.calls.CollectDetails = append(mock.calls.CollectDetails, callInfo)
	mock.lockCollectDetails.Unlock()
	return mock.CollectDetailsFunc(ctx, info, scope)
}

// CollectDetailsCalls gets all the calls that were made to CollectDetails.
// Check the length with:
//
//	len(mockedEngineer.CollectDetailsCalls())
func (mock *MockEngineer) CollectDetailsCalls() []struct {
	Ctx   context.Context
	Info  *models.RepoInfo
	Scope models.ActionSuggestion
} {
	var calls []struct {
		Ctx   context.Context
		Info  *models.RepoInfo
		Scope models.ActionSuggestion
	}
	mock.lockCollectDetails.RLock()
	calls = mock.calls.CollectDetails
	mock.lockCollectDetails.RUnlock()
	return calls
}

// Evaluate calls EvaluateFunc.
func (mock *MockEngineer) Evaluate(ctx context.Context, info *models.RepoInfo, opts ...models.EvaluateOption) (iter.Seq[models.Alert], error) {
	if mock.EvaluateFunc == nil {
		panic("MockEngineer.EvaluateFunc: method is nil but Engineer.Evaluate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Info *models.RepoInfo
		Opts []models.EvaluateOption
	}{
		Ctx:  ctx,
		Info: info,
		Opts: opts,
	}
	mock.lockEvaluate.Lock()
	mock.calls.Evaluate = append(mock.calls.Evaluate, callInfo)
	mock.lockEvaluate.Unlock()
	return mock.EvaluateFunc(ctx, info, opts...)
}

// EvaluateCalls gets all the calls that were made to Evaluate.
// Check the length with:
//
//	len(mockedEngineer.EvaluateCalls())
func (mock *MockEngineer) EvaluateCalls() []struct {
	Ctx  context.Context
	Info *models.RepoInfo
	Opts []models.EvaluateOption
} {
	var calls []struct {
		Ctx  context.Context
		Info *models.RepoInfo
		Opts []models.EvaluateOption
	}
	mock.lockEvaluate.RLock()
	calls = mock.calls.Evaluate
	mock.lockEvaluate.RUnlock()
	return calls
}

// Execute calls ExecuteFunc.
func (mock *MockEngineer) Execute(ctx context.Context, info *models.RepoInfo, action models.ActionSuggestion) (models.Result, error) {
	if mock.ExecuteFunc == nil {
		panic("MockEngineer.ExecuteFunc: method is nil but Engineer.Execute was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Info   *models.RepoInfo
		Action models.ActionSuggestion
	}{
		Ctx:    ctx,
		Info:   info,
		Action: action,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(ctx, info, action)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedEngineer.ExecuteCalls())
func (mock *MockEngineer) ExecuteCalls() []struct {
	Ctx    context.Context
	Info   *models.RepoInfo
	Action models.ActionSuggestion
} {
	var calls []struct {
		Ctx    context.Context
		Info   *models.RepoInfo
		Action models.ActionSuggestion
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}

// ExecuteQuickAction calls ExecuteQuickActionFunc.
func (mock *MockEngineer) ExecuteQuickAction(ctx context.Context, rootIndex int, name string, params map[string]string) error {
	if mock.ExecuteQuickActionFunc == nil {
		panic("MockEngineer.ExecuteQuickActionFunc: method is nil but Engineer.ExecuteQuickAction was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		RootIndex int
		Name      string
		Params    map[string]string
	}{
		Ctx:       ctx,
		RootIndex: rootIndex,
		Name:      name,
		Params:    params,
	}
	mock.lockExecuteQuickAction.Lock()
	mock.calls.ExecuteQuickAction = append(mock.calls.ExecuteQuickAction, callInfo)
	mock.lockExecuteQuickAction.Unlock()
	return mock.ExecuteQuickActionFunc(ctx, rootIndex, name, params)
}

// ExecuteQuickActionCalls gets all the calls that were made to ExecuteQuickAction.
// Check the length with:
//
//	len(mockedEngineer.ExecuteQuickActionCalls())
func (mock *MockEngineer) ExecuteQuickActionCalls() []struct {
	Ctx       context.Context
	RootIndex int
	Name      string
	Params    map[string]string
} {
	var calls []struct {
		Ctx       context.Context
		RootIndex int
		Name      string
		Params    map[string]string
	}
	mock.lockExecuteQuickAction.RLock()
	calls = mock.calls.ExecuteQuickAction
	mock.lockExecuteQuickAction.RUnlock()
	return calls
}

// GetAction calls GetActionFunc.
func (mock *MockEngineer) GetAction(name string) (ifaces.Action, bool) {
	if mock.GetActionFunc == nil {
		panic("MockEngineer.GetActionFunc: method is nil but Engineer.GetAction was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockGetAction.Lock()
	mock.calls.GetAction = append(mock.calls.GetAction, callInfo)
	mock.lockGetAction.Unlock()
	return mock.GetActionFunc(name)
}

// GetActionCalls gets all the calls that were made to GetAction.
// Check the length with:
//
//	len(mockedEngineer.GetActionCalls())
func (mock *MockEngineer) GetActionCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockGetAction.RLock()
	calls = mock.calls.GetAction
	mock.lockGetAction.RUnlock()
	return calls
}

// GetCheck calls GetCheckFunc.
func (mock *MockEngineer) GetCheck(name string) (ifaces.Check, bool) {
	if mock.GetCheckFunc == nil {
		panic("MockEngineer.GetCheckFunc: method is nil but Engineer.GetCheck was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockGetCheck.Lock()
	mock.calls.GetCheck = append(mock.calls.GetCheck, callInfo)
	mock.lockGetCheck.Unlock()
	return mock.GetCheckFunc(name)
}

// GetCheckCalls gets all the calls that were made to GetCheck.
// Check the length with:
//
//	len(mockedEngineer.GetCheckCalls())
func (mock *MockEngineer) GetCheckCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockGetCheck.RLock()
	calls = mock.calls.GetCheck
	mock.lockGetCheck.RUnlock()
	return calls
}

// ProviderEnabled calls ProviderEnabledFunc.
func (mock *MockEngineer) ProviderEnabled(provider string) bool {
	if mock.ProviderEnabledFunc == nil {
		panic("MockEngineer.ProviderEnabledFunc: method is nil but Engineer.ProviderEnabled was just called")
	}
	callInfo := struct {
		Provider string
	}{
		Provider: provider,
	}
	mock.lockProviderEnabled.Lock()
	mock.calls.ProviderEnabled = append(mock.calls.ProviderEnabled, callInfo)
	mock.lockProviderEnabled.Unlock()
	return mock.ProviderEnabledFunc(provider)
}

// ProviderEnabledCalls gets all the calls that were made to ProviderEnabled.
// Check the length with:
//
//	len(mockedEngineer.ProviderEnabledCalls())
func (mock *MockEngineer) ProviderEnabledCalls() []struct {
	Provider string
} {
	var calls []struct {
		Provider string
	}
	mock.lockProviderEnabled.RLock()
	calls = mock.calls.ProviderEnabled
	mock.lockProviderEnabled.RUnlock()
	return calls
}

// PurgeHistory calls PurgeHistoryFunc.
func (mock *MockEngineer) PurgeHistory(olderThanDays int) (int, error) {
	if mock.PurgeHistoryFunc == nil {
		panic("MockEngineer.PurgeHistoryFunc: method is nil but Engineer.PurgeHistory was just called")
	}
	callInfo := struct {
		OlderThanDays int
	}{
		OlderThanDays: olderThanDays,
	}
	mock.lockPurgeHistory.Lock()
	mock.calls.PurgeHistory = append(mock.calls.PurgeHistory, callInfo)
	mock.lockPurgeHistory.Unlock()
	return mock.PurgeHistoryFunc(olderThanDays)
}

// PurgeHistoryCalls gets all the calls that were made to PurgeHistory.
// Check the length with:
//
//	len(mockedEngineer.PurgeHistoryCalls())
func (mock *MockEngineer) PurgeHistoryCalls() []struct {
	OlderThanDays int
} {
	var calls []struct {
		OlderThanDays int
	}
	mock.lockPurgeHistory.RLock()
	calls = mock.calls.PurgeHistory
	mock.lockPurgeHistory.RUnlock()
	return calls
}

// QuickActionsFor calls QuickActionsForFunc.
func (mock *MockEngineer) QuickActionsFor(rootIndex int, subject models.SubjectKind) iter.Seq[*quickactions.QuickAction] {
	if mock.QuickActionsForFunc == nil {
		panic("MockEngineer.QuickActionsForFunc: method is nil but Engineer.QuickActionsFor was just called")
	}
	callInfo := struct {
		RootIndex int
		Subject   models.SubjectKind
	}{
		RootIndex: rootIndex,
		Subject:   subject,
	}
	mock.lockQuickActionsFor.Lock()
	mock.calls.QuickActionsFor = append(mock.calls.QuickActionsFor, callInfo)
	mock.lockQuickActionsFor.Unlock()
	return mock.QuickActionsForFunc(rootIndex, subject)
}

// QuickActionsForCalls gets all the calls that were made to QuickActionsFor.
// Check the length with:
//
//	len(mockedEngineer.QuickActionsForCalls())
func (mock *MockEngineer) QuickActionsForCalls() []struct {
	RootIndex int
	Subject   models.SubjectKind
} {
	var calls []struct {
		RootIndex int
		Subject   models.SubjectKind
	}
	mock.lockQuickActionsFor.RLock()
	calls = mock.calls.QuickActionsFor
	mock.lockQuickActionsFor.RUnlock()
	return calls
}

// RecentHistory calls RecentHistoryFunc.
func (mock *MockEngineer) RecentHistory(repoPath string, since time.Time) []models.HistoryEntry {
	if mock.RecentHistoryFunc == nil {
		panic("MockEngineer.RecentHistoryFunc: method is nil but Engineer.RecentHistory was just called")
	}
	callInfo := struct {
		RepoPath string
		Since    time.Time
	}{
		RepoPath: repoPath,
		Since:    since,
	}
	mock.lockRecentHistory.Lock()
	mock.calls.RecentHistory = append(mock.calls.RecentHistory, callInfo)
	mock.lockRecentHistory.Unlock()
	return mock.RecentHistoryFunc(repoPath, since)
}

// RecentHistoryCalls gets all the calls that were made to RecentHistory.
// Check the length with:
//
//	len(mockedEngineer.RecentHistoryCalls())
func (mock *MockEngineer) RecentHistoryCalls() []struct {
	RepoPath string
	Since    time.Time
} {
	var calls []struct {
		RepoPath string
		Since    time.Time
	}
	mock.lockRecentHistory.RLock()
	calls = mock.calls.RecentHistory
	mock.lockRecentHistory.RUnlock()
	return calls
}

// Refresh calls RefreshFunc.
func (mock *MockEngineer) Refresh(ctx context.Context, info *models.RepoInfo) *models.RepoInfo {
	if mock.RefreshFunc == nil {
		panic("MockEngineer.RefreshFunc: method is nil but Engineer.Refresh was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Info *models.RepoInfo
	}{
		Ctx:  ctx,
		Info: info,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, info)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedEngineer.RefreshCalls())
func (mock *MockEngineer) RefreshCalls() []struct {
	Ctx  context.Context
	Info *models.RepoInfo
} {
	var calls []struct {
		Ctx  context.Context
		Info *models.RepoInfo
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Reload calls ReloadFunc.
func (mock *MockEngineer) Reload(cfg *config.Config) {
	if mock.ReloadFunc == nil {
		panic("MockEngineer.ReloadFunc: method is nil but Engineer.Reload was just called")
	}
	callInfo := struct {
		Cfg *config.Config
	}{
		Cfg: cfg,
	}
	mock.lockReload.Lock()
	mock.calls.Reload = append(mock.calls.Reload, callInfo)
	mock.lockReload.Unlock()
	mock.ReloadFunc(cfg)
}

// ReloadCalls gets all the calls that were made to Reload.
// Check the length with:
//
//	len(mockedEngineer.ReloadCalls())
func (mock *MockEngineer) ReloadCalls() []struct {
	Cfg *config.Config
} {
	var calls []struct {
		Cfg *config.Config
	}
	mock.lockReload.RLock()
	calls = mock.calls.Reload
	mock.lockReload.RUnlock()
	return calls
}

// Ensure that MockSelfDescribed does implement ifaces.SelfDescribed.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.SelfDescribed = &MockSelfDescribed{}

// MockSelfDescribed is a mock implementation of ifaces.SelfDescribed.
//
//	func TestSomethingThatUsesSelfDescribed(t *testing.T) {
//
//		// make and configure a mocked ifaces.SelfDescribed
//		mockedSelfDescribed := &MockSelfDescribed{
//			DescriptionFunc: func() string {
//				panic("mock out the Description method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedSelfDescribed in code that requires ifaces.SelfDescribed
//		// and then make assertions.
//
//	}
type MockSelfDescribed struct {
	// DescriptionFunc mocks the Description method.
	DescriptionFunc func() string

	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Description holds details about calls to the Description method.
		Description []struct {
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockDescription sync.RWMutex
	lockName        sync.RWMutex
}

// Description calls DescriptionFunc.
func (mock *MockSelfDescribed) Description() string {
	if mock.DescriptionFunc == nil {
		panic("MockSelfDescribed.DescriptionFunc: method is nil but SelfDescribed.Description was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDescription.Lock()
	mock.calls.Description = append(mock.calls.Description, callInfo)
	mock.lockDescription.Unlock()
	return mock.DescriptionFunc()
}

// DescriptionCalls gets all the calls that were made to Description.
// Check the length with:
//
//	len(mockedSelfDescribed.DescriptionCalls())
func (mock *MockSelfDescribed) DescriptionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDescription.RLock()
	calls = mock.calls.Description
	mock.lockDescription.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *MockSelfDescribed) Name() string {
	if mock.NameFunc == nil {
		panic("MockSelfDescribed.NameFunc: method is nil but SelfDescribed.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedSelfDescribed.NameCalls())
func (mock *MockSelfDescribed) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Ensure that MockCheck does implement ifaces.Check.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.Check = &MockCheck{}

// MockCheck is a mock implementation of ifaces.Check.
//
//	func TestSomethingThatUsesCheck(t *testing.T) {
//
//		// make and configure a mocked ifaces.Check
//		mockedCheck := &MockCheck{
//			DescriptionFunc: func() string {
//				panic("mock out the Description method")
//			},
//			EvaluateFunc: func(ctx context.Context, info *models.RepoInfo) (iter.Seq[models.Alert], error) {
//				panic("mock out the Evaluate method")
//			},
//			KindFunc: func() models.CheckKind {
//				panic("mock out the Kind method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedCheck in code that requires ifaces.Check
//		// and then make assertions.
//
//	}
type MockCheck struct {
	// DescriptionFunc mocks the Description method.
	DescriptionFunc func() string

	// EvaluateFunc mocks the Evaluate method.
	EvaluateFunc func(ctx context.Context, info *models.RepoInfo) (iter.Seq[models.Alert], error)

	// KindFunc mocks the Kind method.
	KindFunc func() models.CheckKind

	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Description holds details about calls to the Description method.
		Description []struct {
		}
		// Evaluate holds details about calls to the Evaluate method.
		Evaluate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Info is the info argument value.
			Info *models.RepoInfo
		}
		// Kind holds details about calls to the Kind method.
		Kind []struct {
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockDescription sync.RWMutex
	lockEvaluate    sync.RWMutex
	lockKind        sync.RWMutex
	lockName        sync.RWMutex
}

// Description calls DescriptionFunc.
func (mock *MockCheck) Description() string {
	if mock.DescriptionFunc == nil {
		panic("MockCheck.DescriptionFunc: method is nil but Check.Description was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDescription.Lock()
	mock.calls.Description = append(mock.calls.Description, callInfo)
	mock.lockDescription.Unlock()
	return mock.DescriptionFunc()
}

// DescriptionCalls gets all the calls that were made to Description.
// Check the length with:
//
//	len(mockedCheck.DescriptionCalls())
func (mock *MockCheck) DescriptionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDescription.RLock()
	calls = mock.calls.Description
	mock.lockDescription.RUnlock()
	return calls
}

// Evaluate calls EvaluateFunc.
func (mock *MockCheck) Evaluate(ctx context.Context, info *models.RepoInfo) (iter.Seq[models.Alert], error) {
	if mock.EvaluateFunc == nil {
		panic("MockCheck.EvaluateFunc: method is nil but Check.Evaluate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Info *models.RepoInfo
	}{
		Ctx:  ctx,
		Info: info,
	}
	mock.lockEvaluate.Lock()
	mock.calls.Evaluate = append(mock.calls.Evaluate, callInfo)
	mock.lockEvaluate.Unlock()
	return mock.EvaluateFunc(ctx, info)
}

// EvaluateCalls gets all the calls that were made to Evaluate.
// Check the length with:
//
//	len(mockedCheck.EvaluateCalls())
func (mock *MockCheck) EvaluateCalls() []struct {
	Ctx  context.Context
	Info *models.RepoInfo
} {
	var calls []struct {
		Ctx  context.Context
		Info *models.RepoInfo
	}
	mock.lockEvaluate.RLock()
	calls = mock.calls.Evaluate
	mock.lockEvaluate.RUnlock()
	return calls
}

// Kind calls KindFunc.
func (mock *MockCheck) Kind() models.CheckKind {
	if mock.KindFunc == nil {
		panic("MockCheck.KindFunc: method is nil but Check.Kind was just called")
	}
	callInfo := struct {
	}{}
	mock.lockKind.Lock()
	mock.calls.Kind = append(mock.calls.Kind, callInfo)
	mock.lockKind.Unlock()
	return mock.KindFunc()
}

// KindCalls gets all the calls that were made to Kind.
// Check the length with:
//
//	len(mockedCheck.KindCalls())
func (mock *MockCheck) KindCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockKind.RLock()
	calls = mock.calls.Kind
	mock.lockKind.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *MockCheck) Name() string {
	if mock.NameFunc == nil {
		panic("MockCheck.NameFunc: method is nil but Check.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedCheck.NameCalls())
func (mock *MockCheck) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Ensure that MockAction does implement ifaces.Action.
// If this is not the case, regenerate this file with mockery.
var _ ifaces.Action = &MockAction{}

// MockAction is a mock implementation of ifaces.Action.
//
//	func TestSomethingThatUsesAction(t *testing.T) {
//
//		// make and configure a mocked ifaces.Action
//		mockedAction := &MockAction{
//			ApplyToFunc: func() models.SubjectKind {
//				panic("mock out the ApplyTo method")
//			},
//			DescriptionFunc: func() string {
//				panic("mock out the Description method")
//			},
//			DestructiveFunc: func() bool {
//				panic("mock out the Destructive method")
//			},
//			ExecuteFunc: func(ctx context.Context, info *models.RepoInfo, params []string) (models.Result, error) {
//				panic("mock out the Execute method")
//			},
//			KindFunc: func() models.ActionKind {
//				panic("mock out the Kind method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			ParamPromptFunc: func() string {
//				panic("mock out the ParamPrompt method")
//			},
//		}
//
//		// use mockedAction in code that requires ifaces.Action
//		// and then make assertions.
//
//	}
type MockAction struct {
	// ApplyToFunc mocks the ApplyTo method.
	ApplyToFunc func() models.SubjectKind

	// DescriptionFunc mocks the Description method.
	DescriptionFunc func() string

	// DestructiveFunc mocks the Destructive method.
	DestructiveFunc func() bool

	// ExecuteFunc mocks the Execute method.
	ExecuteFunc func(ctx context.Context, info *models.RepoInfo, params []string) (models.Result, error)

	// KindFunc mocks the Kind method.
	KindFunc func() models.ActionKind

	// NameFunc mocks the Name method.
	NameFunc func() string

	// ParamPromptFunc mocks the ParamPrompt method.
	ParamPromptFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// ApplyTo holds details about calls to the ApplyTo method.
		ApplyTo []struct {
		}
		// Description holds details about calls to the Description method.
		Description []struct {
		}
		// Destructive holds details about calls to the Destructive method.
		Destructive []struct {
		}
		// Execute holds details about calls to the Execute method.
		Execute []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Info is the info argument value.
			Info *models.RepoInfo
			// Params is the params argument value.
			Params []string
		}
		// Kind holds details about calls to the Kind method.
		Kind []struct {
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// ParamPrompt holds details about calls to the ParamPrompt method.
		ParamPrompt []struct {
		}
	}
	lockApplyTo     sync.RWMutex
	lockDescription sync.RWMutex
	lockDestructive sync.RWMutex
	lockExecute     sync.RWMutex
	lockKind        sync.RWMutex
	lockName        sync.RWMutex
	lockParamPrompt sync.RWMutex
}

// ApplyTo calls ApplyToFunc.
func (mock *MockAction) ApplyTo() models.SubjectKind {
	if mock.ApplyToFunc == nil {
		panic("MockAction.ApplyToFunc: method is nil but Action.ApplyTo was just called")
	}
	callInfo := struct {
	}{}
	mock.lockApplyTo.Lock()
	mock.calls.ApplyTo = append(mock.calls.ApplyTo, callInfo)
	mock.lockApplyTo.Unlock()
	return mock.ApplyToFunc()
}

// ApplyToCalls gets all the calls that were made to ApplyTo.
// Check the length with:
//
//	len(mockedAction.ApplyToCalls())
func (mock *MockAction) ApplyToCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockApplyTo.RLock()
	calls = mock.calls.ApplyTo
	mock.lockApplyTo.RUnlock()
	return calls
}

// Description calls DescriptionFunc.
func (mock *MockAction) Description() string {
	if mock.DescriptionFunc == nil {
		panic("MockAction.DescriptionFunc: method is nil but Action.Description was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDescription.Lock()
	mock.calls.Description = append(mock.calls.Description, callInfo)
	mock.lockDescription.Unlock()
	return mock.DescriptionFunc()
}

// DescriptionCalls gets all the calls that were made to Description.
// Check the length with:
//
//	len(mockedAction.DescriptionCalls())
func (mock *MockAction) DescriptionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDescription.RLock()
	calls = mock.calls.Description
	mock.lockDescription.RUnlock()
	return calls
}

// Destructive calls DestructiveFunc.
func (mock *MockAction) Destructive() bool {
	if mock.DestructiveFunc == nil {
		panic("MockAction.DestructiveFunc: method is nil but Action.Destructive was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDestructive.Lock()
	mock.calls.Destructive = append(mock.calls.Destructive, callInfo)
	mock.lockDestructive.Unlock()
	return mock.DestructiveFunc()
}

// DestructiveCalls gets all the calls that were made to Destructive.
// Check the length with:
//
//	len(mockedAction.DestructiveCalls())
func (mock *MockAction) DestructiveCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDestructive.RLock()
	calls = mock.calls.Destructive
	mock.lockDestructive.RUnlock()
	return calls
}

// Execute calls ExecuteFunc.
func (mock *MockAction) Execute(ctx context.Context, info *models.RepoInfo, params []string) (models.Result, error) {
	if mock.ExecuteFunc == nil {
		panic("MockAction.ExecuteFunc: method is nil but Action.Execute was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Info   *models.RepoInfo
		Params []string
	}{
		Ctx:    ctx,
		Info:   info,
		Params: params,
	}
	mock.lockExecute.Lock()
	mock.calls.Execute = append(mock.calls.Execute, callInfo)
	mock.lockExecute.Unlock()
	return mock.ExecuteFunc(ctx, info, params)
}

// ExecuteCalls gets all the calls that were made to Execute.
// Check the length with:
//
//	len(mockedAction.ExecuteCalls())
func (mock *MockAction) ExecuteCalls() []struct {
	Ctx    context.Context
	Info   *models.RepoInfo
	Params []string
} {
	var calls []struct {
		Ctx    context.Context
		Info   *models.RepoInfo
		Params []string
	}
	mock.lockExecute.RLock()
	calls = mock.calls.Execute
	mock.lockExecute.RUnlock()
	return calls
}

// Kind calls KindFunc.
func (mock *MockAction) Kind() models.ActionKind {
	if mock.KindFunc == nil {
		panic("MockAction.KindFunc: method is nil but Action.Kind was just called")
	}
	callInfo := struct {
	}{}
	mock.lockKind.Lock()
	mock.calls.Kind = append(mock.calls.Kind, callInfo)
	mock.lockKind.Unlock()
	return mock.KindFunc()
}

// KindCalls gets all the calls that were made to Kind.
// Check the length with:
//
//	len(mockedAction.KindCalls())
func (mock *MockAction) KindCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockKind.RLock()
	calls = mock.calls.Kind
	mock.lockKind.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *MockAction) Name() string {
	if mock.NameFunc == nil {
		panic("MockAction.NameFunc: method is nil but Action.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedAction.NameCalls())
func (mock *MockAction) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// ParamPrompt calls ParamPromptFunc.
func (mock *MockAction) ParamPrompt() string {
	if mock.ParamPromptFunc == nil {
		panic("MockAction.ParamPromptFunc: method is nil but Action.ParamPrompt was just called")
	}
	callInfo := struct {
	}{}
	mock.lockParamPrompt.Lock()
	mock.calls.ParamPrompt = append(mock.calls.ParamPrompt, callInfo)
	mock.lockParamPrompt.Unlock()
	return mock.ParamPromptFunc()
}

// ParamPromptCalls gets all the calls that were made to ParamPrompt.
// Check the length with:
//
//	len(mockedAction.ParamPromptCalls())
func (mock *MockAction) ParamPromptCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockParamPrompt.RLock()
	calls = mock.calls.ParamPrompt
	mock.lockParamPrompt.RUnlock()
	return calls
}
